# Generated by Django 6.0.3 on 2026-04-09 08:25

import endoreg_db.models.media.video.storage_mode
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "endoreg_db",
            "0014_sensitivemeta_tags_sensitivemeta_validation_comment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadjob",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Canonical content hash used for content-first deduplication.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="processed_streamable_relative_path",
            field=models.CharField(
                blank=True,
                help_text="Protected-media relative path for the processed streamable asset when storage_mode = fs_encrypted_streamable.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="storage_mode",
            field=models.CharField(
                choices=[
                    ("app_encrypted", "Application Encrypted"),
                    ("fs_encrypted_streamable", "Filesystem Encrypted Streamable"),
                ],
                default=endoreg_db.models.media.video.storage_mode.get_default_video_storage_mode_value,
                help_text="Controls whether this video stays on the legacy application-encrypted streaming path or may be handed off to Nginx from an encrypted filesystem-backed media root.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="streamable_relative_path",
            field=models.CharField(
                blank=True,
                help_text="Protected-media relative path for the raw streamable asset when storage_mode = fs_encrypted_streamable.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("anonymized", "Anonymized"),
                    ("error", "Error"),
                    ("lost", "Lost"),
                ],
                default="pending",
                help_text="Current processing status of the upload",
                max_length=20,
            ),
        ),
    ]
