# Generated by Django 6.0.3 on 2026-04-21 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0015_uploadjob_content_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="videofile",
            old_name="streamable_relative_path",
            new_name="raw_streamable_relative_path",
        ),
        migrations.AddField(
            model_name="aidataset",
            name="video_annotations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Video-segment annotations collected from the video examination annotation workflow.",
                related_name="video_ai_datasets",
                to="endoreg_db.labelvideosegment",
            ),
        ),
        migrations.AddField(
            model_name="applicationsettings",
            name="ai_dataset_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="applicationsettings",
            name="ai_dataset_type",
            field=models.CharField(
                blank=True,
                choices=[("", "Unset"), ("image", "Image"), ("video", "Video")],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="aidataset",
            name="ai_model_type",
            field=models.CharField(
                default="image_multilabel_classification",
                help_text='AI model family this dataset is for, e.g. "image_multilabel_classification".',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="aidataset",
            name="dataset_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                help_text="Primary annotation modality used for training. Export helpers may still include both frame and video annotations attached to the dataset.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="aidataset",
            name="image_annotations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Frame-level annotations collected from the frame annotation workflow.",
                related_name="image_ai_datasets",
                to="endoreg_db.imageclassificationannotation",
            ),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="endoscope_image_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="endoscope_image_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="endoscope_image_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="endoscope_image_y",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="examination_date_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="examination_date_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="examination_date_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="examination_date_y",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="image_height",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="image_width",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_dob_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_dob_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_dob_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_dob_y",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_first_name_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_first_name_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_first_name_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_first_name_y",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_last_name_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_last_name_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_last_name_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="endoscopyprocessor",
            name="patient_last_name_y",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="uploadjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("content_hash", ""), _negated=True),
                    models.Q(("status__in", ["error", "lost"]), _negated=True),
                ),
                fields=("source_center", "content_type", "content_hash"),
                name="uniq_uploadjob_content_hash_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("idempotency_key", ""), _negated=True),
                    models.Q(("status__in", ["error", "lost"]), _negated=True),
                ),
                fields=(
                    "source_center",
                    "source_system",
                    "ingest_mode",
                    "storage_class",
                    "storage_tier",
                    "idempotency_key",
                ),
                name="uniq_uploadjob_idempotency_scope_active",
            ),
        ),
    ]
