# Generated by Django 6.0.3 on 2026-04-30 07:58

import django.core.validators
import endoreg_db.utils.encryption.encrypted
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0017_auditledger_ledgerhead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawpdffile",
            name="file",
            field=models.FileField(
                storage=endoreg_db.utils.encryption.encrypted.LazyEncryptedStorage(),
                upload_to="sensitive_reports",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rawpdffile",
            name="processed_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=endoreg_db.utils.encryption.encrypted.LazyEncryptedStorage(),
                upload_to="processed_reports_final",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="processed_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=endoreg_db.utils.encryption.encrypted.LazyEncryptedStorage(),
                upload_to="processed_videos_final",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="raw_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=endoreg_db.utils.encryption.encrypted.LazyEncryptedStorage(),
                upload_to="sensitive_videos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
