# Generated by Django 6.0.3 on 2026-05-12 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0019_videostate_outside_segments_removed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoprocessinghistory",
            name="operation",
            field=models.CharField(
                choices=[
                    ("mask_overlay", "Mask Overlay"),
                    ("frame_removal", "Frame Removal"),
                    ("analysis", "Sensitivity Analysis"),
                    ("reprocessing", "Full Reprocessing"),
                    ("ai_temporal_inference", "AI Temporal Inference"),
                ],
                help_text="Type of processing operation",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AIDataSetExportArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "dataset_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dataset_type", models.CharField(blank=True, max_length=32)),
                ("ai_model_type", models.CharField(blank=True, max_length=255)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("center_key", models.CharField(blank=True, max_length=255, null=True)),
                ("all_centers", models.BooleanField(default=False)),
                ("only_validated", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                ("output_path", models.TextField(blank=True)),
                ("download_filename", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("byte_size", models.PositiveBigIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_artifacts",
                        to="endoreg_db.aidataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="aid_export_status_idx"
                    ),
                    models.Index(
                        fields=["dataset", "-created_at"], name="aid_export_dataset_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIModelTrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "dataset_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dataset_type", models.CharField(blank=True, max_length=32)),
                ("ai_model_type", models.CharField(blank=True, max_length=255)),
                ("backbone_name", models.CharField(max_length=128)),
                ("feature_mode", models.CharField(max_length=64)),
                ("freeze_backbone", models.BooleanField(default=True)),
                ("epochs", models.PositiveIntegerField(default=10)),
                ("batch_size", models.PositiveIntegerField(default=32)),
                ("labelset_version", models.PositiveIntegerField(default=1)),
                ("treat_unlabeled_as_negative", models.BooleanField(default=True)),
                ("backbone_checkpoint", models.TextField(blank=True, null=True)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("command_kwargs", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "server_instance_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("artifact_paths", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("stdout", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_training_runs",
                        to="endoreg_db.aidataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="aid_train_status_idx"
                    ),
                    models.Index(
                        fields=["server_instance_id", "status"],
                        name="aid_train_server_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FrameBoxAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("image_width", models.PositiveIntegerField()),
                ("image_height", models.PositiveIntegerField()),
                ("value", models.BooleanField(default=True)),
                ("float_value", models.FloatField(blank=True, null=True)),
                ("annotator", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "external_annotation_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_annotations",
                        to="endoreg_db.frame",
                    ),
                ),
                (
                    "information_source",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frame_box_annotations",
                        to="endoreg_db.informationsource",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame_box_annotations",
                        to="endoreg_db.label",
                    ),
                ),
                (
                    "model_meta",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frame_box_annotations",
                        to="endoreg_db.modelmeta",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["frame", "label"], name="endoreg_db__frame_i_54216f_idx"
                    ),
                    models.Index(
                        fields=["frame", "information_source", "annotator"],
                        name="endoreg_db__frame_i_27e48c_idx",
                    ),
                    models.Index(
                        fields=["external_annotation_id"],
                        name="endoreg_db__externa_c50e13_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("x__gte", 0)),
                        name="frame_box_x_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("y__gte", 0)),
                        name="frame_box_y_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("width__gt", 0)),
                        name="frame_box_width_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("height__gt", 0)),
                        name="frame_box_height_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("image_width__gt", 0)),
                        name="frame_box_image_width_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("image_height__gt", 0)),
                        name="frame_box_image_height_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FrameExtractionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame_extraction_requests",
                        to="endoreg_db.videofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frame Extraction Request",
                "verbose_name_plural": "Frame Extraction Requests",
                "db_table": "frame_extraction_request",
                "indexes": [
                    models.Index(
                        fields=["video", "frame_number"],
                        name="frame_extra_video_i_e672aa_idx",
                    ),
                    models.Index(
                        fields=["status"], name="frame_extra_status_7c6393_idx"
                    ),
                    models.Index(
                        fields=["task_id"], name="frame_extra_task_id_566a3b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("video", "frame_number"),
                        name="uniq_frame_extraction_request_video_frame",
                    )
                ],
            },
        ),
    ]
