# Generated by Django 6.0.3 on 2026-05-22 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "endoreg_db",
            "0022_anonymizationvalidationmetric_missing_sensitive_meta_deletion_count_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLlmInferenceJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("report_llm_reimport", "Report LLM Reimport"),
                            ("report_llm_import", "Report LLM Import"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("lost", "Lost"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("queue", models.CharField(max_length=64)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "report_llm_inference_job",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("processing_error", False),
                    ("processing_started", False),
                    _connector="OR",
                ),
                name="videostate_failed_not_started",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("processing_error", False),
                    _connector="OR",
                ),
                name="videostate_ready_not_failed",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("anonymization_validated", True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_validation",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("outside_segments_removed", True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_cleanup",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("segment_annotations_validated", True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_segments",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    ("ready_for_export_at__isnull", False),
                    _connector="OR",
                ),
                name="videostate_ready_requires_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    models.Q(("ready_for_export_by", ""), _negated=True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="videostate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ready_for_export", False),
                    models.Q(("processed_file_sha256", ""), _negated=True),
                    _connector="OR",
                ),
                name="videostate_ready_requires_sha",
            ),
        ),
        migrations.AddField(
            model_name="reportllminferencejob",
            name="pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_inference_jobs",
                to="endoreg_db.rawpdffile",
            ),
        ),
        migrations.AddField(
            model_name="reportllminferencejob",
            name="upload_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_llm_inference_jobs",
                to="endoreg_db.uploadjob",
            ),
        ),
        migrations.AddIndex(
            model_name="reportllminferencejob",
            index=models.Index(
                fields=["pdf", "operation", "status"],
                name="report_llm__pdf_id_6995a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportllminferencejob",
            index=models.Index(
                fields=["upload_job", "operation", "status"],
                name="report_llm__upload__55849f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportllminferencejob",
            index=models.Index(
                fields=["queue", "status"], name="report_llm__queue_27d75f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportllminferencejob",
            index=models.Index(
                fields=["status", "-created_at"], name="report_llm__status_188b9e_idx"
            ),
        ),
    ]
