# Generated by Django 6.0.3 on 2026-05-28 07:56

import django.core.validators
import endoreg_db.utils.encryption.encrypted
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0023_reportllminferencejob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="processed_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=endoreg_db.utils.encryption.encrypted.LazyEncryptedStorage(),
                upload_to="processed_videos_final",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
