# Generated by Django 6.0.3 on 2026-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0024_alter_videofile_processed_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientlabvalue",
            old_name="datetime",
            new_name="timestamp",
        ),
        migrations.AddField(
            model_name="patientexamination",
            name="dtypes_record",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="patientexamination",
            name="dtypes_record_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="end_date",
            field=models.DateTimeField(
                blank=True, help_text="The end date and time of the case.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="hash",
            field=models.CharField(
                blank=True,
                help_text="A hash value associated with the case when configured.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientfindingclassification",
            name="numerical_descriptors",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="patientfindingclassification",
            name="subcategories",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
