# Generated by Django 6.0.3 on 2026-07-09 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0025_rename_datetime_patientlabvalue_timestamp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarantineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.TextField(unique=True)),
                ("relative_path", models.TextField(db_index=True)),
                ("original_filename", models.CharField(blank=True, max_length=512)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("file_mtime_ns", models.BigIntegerField(default=0)),
                ("quarantined_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("retained", "Retained"),
                            ("approved_for_deletion", "Approved For Deletion"),
                            ("deleted", "Deleted"),
                            ("missing", "Missing"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("decision_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("delete_eligible_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_quarantine_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_upload_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quarantine_items",
                        to="endoreg_db.uploadjob",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-quarantined_at", "relative_path"],
                "indexes": [
                    models.Index(
                        fields=["status", "delete_eligible_at"],
                        name="quarantine_status_delete_idx",
                    ),
                    models.Index(
                        fields=["last_seen_at"], name="quarantine_last_seen_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoHlsArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[("raw", "Raw"), ("processed", "Processed")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("materializing", "Materializing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="materializing",
                        max_length=32,
                    ),
                ),
                (
                    "key_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("key_ciphertext", models.BinaryField(blank=True, null=True)),
                ("key_nonce", models.BinaryField(blank=True, null=True)),
                (
                    "key_wrap_algorithm",
                    models.CharField(default="AESGCM-master-wrap-v1", max_length=64),
                ),
                ("iv_hex", models.CharField(blank=True, max_length=32)),
                (
                    "playlist_relative_path",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "segment_directory_relative_path",
                    models.CharField(blank=True, max_length=500),
                ),
                ("segment_count", models.PositiveIntegerField(default=0)),
                ("source_file_name", models.CharField(blank=True, max_length=500)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hls_artifacts",
                        to="endoreg_db.videofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["video", "artifact_kind", "status"],
                        name="endoreg_db__video_i_b05550_idx",
                    ),
                    models.Index(
                        fields=["key_id", "status"],
                        name="endoreg_db__key_id_9f61a0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("video", "artifact_kind"),
                        name="unique_video_hls_artifact_kind",
                    )
                ],
            },
        ),
    ]
