# Generated by Django 6.0.3 on 2026-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0026_quarantineitem_videohlsartifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawpdfstate",
            name="processed_file_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of the plaintext anonymized PDF currently attached to the RawPdfFile. Empty until a processed artifact has been verified.",
                max_length=64,
            ),
        ),
    ]
