# Generated by Django 6.0.3 on 2026-07-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0028_alter_videohlsartifact_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("source_system", models.CharField(max_length=128)),
                ("schema_version", models.PositiveSmallIntegerField(default=2)),
                ("manifest_sha256", models.CharField(max_length=64, unique=True)),
                ("manifest", models.JSONField()),
                ("status_detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DicomInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sop_instance_uid", models.CharField(max_length=64, unique=True)),
                ("sop_class_uid", models.CharField(max_length=64)),
                ("transfer_syntax_uid", models.CharField(max_length=64)),
                ("instance_number", models.PositiveIntegerField(blank=True, null=True)),
                ("artifact_reference", models.CharField(max_length=1024)),
                (
                    "artifact_class",
                    models.CharField(
                        choices=[("anonymized_processed", "Anonymized processed")],
                        max_length=32,
                    ),
                ),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("masked_regions", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["instance_number", "sop_instance_uid"],
            },
        ),
        migrations.CreateModel(
            name="DicomSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_instance_uid", models.CharField(max_length=64, unique=True)),
                ("modality", models.CharField(max_length=16)),
                ("series_number", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["series_number", "series_instance_uid"],
            },
        ),
        migrations.CreateModel(
            name="DicomStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_instance_uid", models.CharField(max_length=64, unique=True)),
                ("patient_pseudonym", models.CharField(max_length=255)),
                (
                    "accession_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("study_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["study_instance_uid"],
            },
        ),
        migrations.AddIndex(
            model_name="frame",
            index=models.Index(
                fields=["video", "timestamp"], name="frame_video_timestamp_idx"
            ),
        ),
        migrations.AddField(
            model_name="dicomexportjob",
            name="patient_examination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dicom_export_jobs",
                to="endoreg_db.patientexamination",
            ),
        ),
        migrations.AddField(
            model_name="dicominstance",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="endoreg_db.dicomseries",
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="export_job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="study",
                to="endoreg_db.dicomexportjob",
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="patient_examination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dicom_studies",
                to="endoreg_db.patientexamination",
            ),
        ),
        migrations.AddField(
            model_name="dicomseries",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="endoreg_db.dicomstudy",
            ),
        ),
        migrations.AddIndex(
            model_name="dicominstance",
            index=models.Index(
                fields=["series", "instance_number"],
                name="endoreg_db__series__9c6c00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dicominstance",
            index=models.Index(
                fields=["artifact_sha256"], name="endoreg_db__artifac_ed4b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomstudy",
            index=models.Index(
                fields=["patient_examination", "study_date"],
                name="endoreg_db__patient_09a610_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dicomseries",
            index=models.Index(
                fields=["study", "modality"], name="endoreg_db__study_i_9a1f92_idx"
            ),
        ),
    ]
