# Generated by Django 6.0.3 on 2026-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0031_uploadjob_error_code_uploadjob_last_attempt_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frame",
            name="presentation_timestamp",
            field=models.BigIntegerField(
                blank=True,
                help_text="Exact presentation timestamp tick in the selected video stream time base.",
                null=True,
            ),
        ),
    ]
