# Generated by Django 6.0.3 on 2026-07-23 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0033_portaluserinfo_centers"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public identifier for the clinical case.",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="patient_lab_samples",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="endoreg_db.patientlabsample"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="patient_lab_values",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="endoreg_db.patientlabvalue"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="patient_medication_schedules",
            field=models.ManyToManyField(
                blank=True,
                related_name="cases",
                to="endoreg_db.patientmedicationschedule",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="patient_medications",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="endoreg_db.patientmedication"
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="case_end_not_before_start",
            ),
        ),
    ]
