# Generated by Django 6.0.3 on 2026-07-27 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0034_case_case_id_case_patient_lab_samples_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportImportAttempt",
            fields=[
                (
                    "content_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("fencing_token", models.PositiveBigIntegerField(default=0)),
                ("owner_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("active", "Active"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=16,
                    ),
                ),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "report_import_attempt",
            },
        ),
        migrations.RemoveConstraint(
            model_name="videohlsartifact",
            name="unique_video_hls_artifact_kind",
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="processing_fencing_token",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Monotonic token fencing stale import workers from state changes.",
            ),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="processing_heartbeat_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Database time of the most recent import-processing heartbeat.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="processing_lease_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Database-time expiry of the current import-processing lease.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="processing_lease_owner",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Opaque worker identity that currently owns import processing.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="videohlsartifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("materializing", "Materializing"),
                    ("validated", "Validated"),
                    ("ready", "Ready"),
                    ("superseded", "Superseded"),
                    ("failed", "Failed"),
                ],
                default="materializing",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="uploadjob",
            index=models.Index(
                fields=["status", "processing_lease_expires_at"],
                name="upload_job_lease_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("processing_heartbeat_at__isnull", True),
                        ("processing_lease_expires_at__isnull", True),
                        ("processing_lease_owner", ""),
                    ),
                    models.Q(
                        models.Q(("processing_lease_owner", ""), _negated=True),
                        ("processing_heartbeat_at__isnull", False),
                        ("processing_lease_expires_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="upload_job_lease_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="videohlsartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ready")),
                fields=("video", "artifact_kind"),
                name="unique_ready_video_hls_artifact_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="videohlsartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["queued", "materializing", "validated"])
                ),
                fields=("video", "artifact_kind"),
                name="unique_active_video_hls_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportimportattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("heartbeat_at__isnull", False),
                        ("lease_expires_at__isnull", False),
                        ("owner_id__isnull", False),
                        ("status", "active"),
                    ),
                    models.Q(
                        models.Q(("status", "active"), _negated=True),
                        ("heartbeat_at__isnull", True),
                        ("lease_expires_at__isnull", True),
                        ("owner_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="report_attempt_lease_state_consistent",
            ),
        ),
    ]
