export interface UploadJobOverview {
    id: string;
    status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
    ingestMode?: 'api' | 'watcher' | string;
    sourceSystem?: string;
    sourceCenterKey?: string | null;
    originalFilename?: string;
    sourceFilePersisted?: boolean;
    cleanupStatus?: 'pending' | 'eligible' | 'completed' | 'skipped' | string;
    errorDetail?: string;
    createdAt?: string | null;
    updatedAt?: string | null;
}
export interface FileItem {
    id: number;
    filename: string;
    mediaType: 'pdf' | 'video' | 'unknown';
    anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
    annotationStatus: 'not_started' | 'validated' | '';
    createdAt: string;
    sensitiveMetaId?: number;
    documentType?: string | null;
    patientHashDisplay?: string | null;
    examinationHashDisplay?: string | null;
    pseudoPatientId?: number | null;
    pseudoExaminationId?: number | null;
    metadataImported?: boolean;
    fileSize?: number | undefined;
    rawFile?: string;
    uploadJob?: UploadJobOverview | null;
    quarantined?: boolean;
    quarantineId?: string;
    quarantineDirectoryKey?: string;
    quarantineDirectoryLabel?: string;
    errorDetail?: string;
}
export interface QuarantineFileItem {
    id: string;
    directoryKey: string;
    directoryLabel: string;
    filename: string;
    mediaType: 'pdf' | 'video' | 'unknown';
    size: number;
    quarantinedAt?: string | null;
    createdAt?: string | null;
    modifiedAt?: string | null;
    reason?: string;
}
export interface QuarantineOverviewResponse {
    count: number;
    totalSize: number;
    files: QuarantineFileItem[];
}
export interface AnonymizationState {
    anonymizationStatus: string;
    loading: boolean;
    error: string | null;
    pending: [boolean];
    current: SensitiveMeta | null;
    overview: FileItem[];
    pollingHandles: Record<number, ReturnType<typeof setInterval>>;
    isPolling: boolean;
    hasAvailableFiles: boolean;
    availableFiles: FileItem[];
    needsValidationIds: number[];
}
export interface SensitiveMeta {
    id: number;
    casenumber?: string | null;
    patientFirstName?: string | null;
    patientLastName?: string | null;
    patientDob?: string | null;
    patientDobDisplay?: string | null;
    patientGender: string;
    examinationDate: string | null;
    centerName?: string;
    patientGenderName?: string;
    examinersDisplay: string | null;
    endoscopeType?: string;
    endoscopeSn?: string;
    isVerified?: boolean;
    dobVerified?: boolean;
    namesVerified?: boolean;
    anonymizedText?: string;
    text?: string;
    documentType?: string | null;
    document_type?: string | null;
    externalId?: string;
    externalIdOrigin?: string;
    tags?: string[];
    validationComment?: string | null;
    validation_comment?: string | null;
    patientHashDisplay?: string | null;
    examinationHashDisplay?: string | null;
    pseudoPatientId?: number | null;
    pseudoExaminationId?: number | null;
    patientExaminationId?: number | null;
    patientId?: number | null;
}
export declare const availableFiles: import("vue").Ref<{
    id: number;
    filename: string;
    mediaType: 'pdf' | 'video' | 'unknown';
    anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
    annotationStatus: 'not_started' | 'validated' | '';
    createdAt: string;
    sensitiveMetaId?: number | undefined;
    documentType?: string | null | undefined;
    patientHashDisplay?: string | null | undefined;
    examinationHashDisplay?: string | null | undefined;
    pseudoPatientId?: number | null | undefined;
    pseudoExaminationId?: number | null | undefined;
    metadataImported?: boolean | undefined;
    fileSize?: number | undefined;
    rawFile?: string | undefined;
    uploadJob?: {
        id: string;
        status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
        ingestMode?: string | undefined;
        sourceSystem?: string | undefined;
        sourceCenterKey?: string | null | undefined;
        originalFilename?: string | undefined;
        sourceFilePersisted?: boolean | undefined;
        cleanupStatus?: string | undefined;
        errorDetail?: string | undefined;
        createdAt?: string | null | undefined;
        updatedAt?: string | null | undefined;
    } | null | undefined;
    quarantined?: boolean | undefined;
    quarantineId?: string | undefined;
    quarantineDirectoryKey?: string | undefined;
    quarantineDirectoryLabel?: string | undefined;
    errorDetail?: string | undefined;
}[], FileItem[] | {
    id: number;
    filename: string;
    mediaType: 'pdf' | 'video' | 'unknown';
    anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
    annotationStatus: 'not_started' | 'validated' | '';
    createdAt: string;
    sensitiveMetaId?: number | undefined;
    documentType?: string | null | undefined;
    patientHashDisplay?: string | null | undefined;
    examinationHashDisplay?: string | null | undefined;
    pseudoPatientId?: number | null | undefined;
    pseudoExaminationId?: number | null | undefined;
    metadataImported?: boolean | undefined;
    fileSize?: number | undefined;
    rawFile?: string | undefined;
    uploadJob?: {
        id: string;
        status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
        ingestMode?: string | undefined;
        sourceSystem?: string | undefined;
        sourceCenterKey?: string | null | undefined;
        originalFilename?: string | undefined;
        sourceFilePersisted?: boolean | undefined;
        cleanupStatus?: string | undefined;
        errorDetail?: string | undefined;
        createdAt?: string | null | undefined;
        updatedAt?: string | null | undefined;
    } | null | undefined;
    quarantined?: boolean | undefined;
    quarantineId?: string | undefined;
    quarantineDirectoryKey?: string | undefined;
    quarantineDirectoryLabel?: string | undefined;
    errorDetail?: string | undefined;
}[]>;
export declare const useAnonymizationStore: import("pinia").StoreDefinition<"anonymization", AnonymizationState, {
    getCurrentItem: (state: {
        anonymizationStatus: string;
        loading: boolean;
        error: string | null;
        pending: [boolean];
        current: {
            id: number;
            casenumber?: string | null | undefined;
            patientFirstName?: string | null | undefined;
            patientLastName?: string | null | undefined;
            patientDob?: string | null | undefined;
            patientDobDisplay?: string | null | undefined;
            patientGender: string;
            examinationDate: string | null;
            centerName?: string | undefined;
            patientGenderName?: string | undefined;
            examinersDisplay: string | null;
            endoscopeType?: string | undefined;
            endoscopeSn?: string | undefined;
            isVerified?: boolean | undefined;
            dobVerified?: boolean | undefined;
            namesVerified?: boolean | undefined;
            anonymizedText?: string | undefined;
            text?: string | undefined;
            documentType?: string | null | undefined;
            document_type?: string | null | undefined;
            externalId?: string | undefined;
            externalIdOrigin?: string | undefined;
            tags?: string[] | undefined;
            validationComment?: string | null | undefined;
            validation_comment?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            patientExaminationId?: number | null | undefined;
            patientId?: number | null | undefined;
        } | null;
        overview: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        pollingHandles: Record<number, ReturnType<typeof setInterval>>;
        isPolling: boolean;
        hasAvailableFiles: boolean;
        availableFiles: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        needsValidationIds: number[];
    } & import("pinia").PiniaCustomStateProperties<AnonymizationState>) => {
        id: number;
        casenumber?: string | null | undefined;
        patientFirstName?: string | null | undefined;
        patientLastName?: string | null | undefined;
        patientDob?: string | null | undefined;
        patientDobDisplay?: string | null | undefined;
        patientGender: string;
        examinationDate: string | null;
        centerName?: string | undefined;
        patientGenderName?: string | undefined;
        examinersDisplay: string | null;
        endoscopeType?: string | undefined;
        endoscopeSn?: string | undefined;
        isVerified?: boolean | undefined;
        dobVerified?: boolean | undefined;
        namesVerified?: boolean | undefined;
        anonymizedText?: string | undefined;
        text?: string | undefined;
        documentType?: string | null | undefined;
        document_type?: string | null | undefined;
        externalId?: string | undefined;
        externalIdOrigin?: string | undefined;
        tags?: string[] | undefined;
        validationComment?: string | null | undefined;
        validation_comment?: string | null | undefined;
        patientHashDisplay?: string | null | undefined;
        examinationHashDisplay?: string | null | undefined;
        pseudoPatientId?: number | null | undefined;
        pseudoExaminationId?: number | null | undefined;
        patientExaminationId?: number | null | undefined;
        patientId?: number | null | undefined;
    } | null;
    isAnyFileProcessing: (state: {
        anonymizationStatus: string;
        loading: boolean;
        error: string | null;
        pending: [boolean];
        current: {
            id: number;
            casenumber?: string | null | undefined;
            patientFirstName?: string | null | undefined;
            patientLastName?: string | null | undefined;
            patientDob?: string | null | undefined;
            patientDobDisplay?: string | null | undefined;
            patientGender: string;
            examinationDate: string | null;
            centerName?: string | undefined;
            patientGenderName?: string | undefined;
            examinersDisplay: string | null;
            endoscopeType?: string | undefined;
            endoscopeSn?: string | undefined;
            isVerified?: boolean | undefined;
            dobVerified?: boolean | undefined;
            namesVerified?: boolean | undefined;
            anonymizedText?: string | undefined;
            text?: string | undefined;
            documentType?: string | null | undefined;
            document_type?: string | null | undefined;
            externalId?: string | undefined;
            externalIdOrigin?: string | undefined;
            tags?: string[] | undefined;
            validationComment?: string | null | undefined;
            validation_comment?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            patientExaminationId?: number | null | undefined;
            patientId?: number | null | undefined;
        } | null;
        overview: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        pollingHandles: Record<number, ReturnType<typeof setInterval>>;
        isPolling: boolean;
        hasAvailableFiles: boolean;
        availableFiles: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        needsValidationIds: number[];
    } & import("pinia").PiniaCustomStateProperties<AnonymizationState>) => boolean;
    processingFiles: (state: {
        anonymizationStatus: string;
        loading: boolean;
        error: string | null;
        pending: [boolean];
        current: {
            id: number;
            casenumber?: string | null | undefined;
            patientFirstName?: string | null | undefined;
            patientLastName?: string | null | undefined;
            patientDob?: string | null | undefined;
            patientDobDisplay?: string | null | undefined;
            patientGender: string;
            examinationDate: string | null;
            centerName?: string | undefined;
            patientGenderName?: string | undefined;
            examinersDisplay: string | null;
            endoscopeType?: string | undefined;
            endoscopeSn?: string | undefined;
            isVerified?: boolean | undefined;
            dobVerified?: boolean | undefined;
            namesVerified?: boolean | undefined;
            anonymizedText?: string | undefined;
            text?: string | undefined;
            documentType?: string | null | undefined;
            document_type?: string | null | undefined;
            externalId?: string | undefined;
            externalIdOrigin?: string | undefined;
            tags?: string[] | undefined;
            validationComment?: string | null | undefined;
            validation_comment?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            patientExaminationId?: number | null | undefined;
            patientId?: number | null | undefined;
        } | null;
        overview: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        pollingHandles: Record<number, ReturnType<typeof setInterval>>;
        isPolling: boolean;
        hasAvailableFiles: boolean;
        availableFiles: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        needsValidationIds: number[];
    } & import("pinia").PiniaCustomStateProperties<AnonymizationState>) => {
        id: number;
        filename: string;
        mediaType: 'pdf' | 'video' | 'unknown';
        anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
        annotationStatus: 'not_started' | 'validated' | '';
        createdAt: string;
        sensitiveMetaId?: number | undefined;
        documentType?: string | null | undefined;
        patientHashDisplay?: string | null | undefined;
        examinationHashDisplay?: string | null | undefined;
        pseudoPatientId?: number | null | undefined;
        pseudoExaminationId?: number | null | undefined;
        metadataImported?: boolean | undefined;
        fileSize?: number | undefined;
        rawFile?: string | undefined;
        uploadJob?: {
            id: string;
            status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
            ingestMode?: string | undefined;
            sourceSystem?: string | undefined;
            sourceCenterKey?: string | null | undefined;
            originalFilename?: string | undefined;
            sourceFilePersisted?: boolean | undefined;
            cleanupStatus?: string | undefined;
            errorDetail?: string | undefined;
            createdAt?: string | null | undefined;
            updatedAt?: string | null | undefined;
        } | null | undefined;
        quarantined?: boolean | undefined;
        quarantineId?: string | undefined;
        quarantineDirectoryKey?: string | undefined;
        quarantineDirectoryLabel?: string | undefined;
        errorDetail?: string | undefined;
    }[];
    getState: (state: {
        anonymizationStatus: string;
        loading: boolean;
        error: string | null;
        pending: [boolean];
        current: {
            id: number;
            casenumber?: string | null | undefined;
            patientFirstName?: string | null | undefined;
            patientLastName?: string | null | undefined;
            patientDob?: string | null | undefined;
            patientDobDisplay?: string | null | undefined;
            patientGender: string;
            examinationDate: string | null;
            centerName?: string | undefined;
            patientGenderName?: string | undefined;
            examinersDisplay: string | null;
            endoscopeType?: string | undefined;
            endoscopeSn?: string | undefined;
            isVerified?: boolean | undefined;
            dobVerified?: boolean | undefined;
            namesVerified?: boolean | undefined;
            anonymizedText?: string | undefined;
            text?: string | undefined;
            documentType?: string | null | undefined;
            document_type?: string | null | undefined;
            externalId?: string | undefined;
            externalIdOrigin?: string | undefined;
            tags?: string[] | undefined;
            validationComment?: string | null | undefined;
            validation_comment?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            patientExaminationId?: number | null | undefined;
            patientId?: number | null | undefined;
        } | null;
        overview: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        pollingHandles: Record<number, ReturnType<typeof setInterval>>;
        isPolling: boolean;
        hasAvailableFiles: boolean;
        availableFiles: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        needsValidationIds: number[];
    } & import("pinia").PiniaCustomStateProperties<AnonymizationState>) => {
        anonymizationStatus: string;
        loading: boolean;
        error: string | null;
        pending: [boolean];
        current: {
            id: number;
            casenumber?: string | null | undefined;
            patientFirstName?: string | null | undefined;
            patientLastName?: string | null | undefined;
            patientDob?: string | null | undefined;
            patientDobDisplay?: string | null | undefined;
            patientGender: string;
            examinationDate: string | null;
            centerName?: string | undefined;
            patientGenderName?: string | undefined;
            examinersDisplay: string | null;
            endoscopeType?: string | undefined;
            endoscopeSn?: string | undefined;
            isVerified?: boolean | undefined;
            dobVerified?: boolean | undefined;
            namesVerified?: boolean | undefined;
            anonymizedText?: string | undefined;
            text?: string | undefined;
            documentType?: string | null | undefined;
            document_type?: string | null | undefined;
            externalId?: string | undefined;
            externalIdOrigin?: string | undefined;
            tags?: string[] | undefined;
            validationComment?: string | null | undefined;
            validation_comment?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            patientExaminationId?: number | null | undefined;
            patientId?: number | null | undefined;
        } | null;
        overview: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        pollingHandles: Record<number, ReturnType<typeof setInterval>>;
        isPolling: boolean;
        hasAvailableFiles: boolean;
        availableFiles: {
            id: number;
            filename: string;
            mediaType: 'pdf' | 'video' | 'unknown';
            anonymizationStatus: 'not_started' | 'processing_anonymization' | 'done_processing_anonymization' | 'failed' | 'validated' | 'predicting_segments' | 'extracting_frames';
            annotationStatus: 'not_started' | 'validated' | '';
            createdAt: string;
            sensitiveMetaId?: number | undefined;
            documentType?: string | null | undefined;
            patientHashDisplay?: string | null | undefined;
            examinationHashDisplay?: string | null | undefined;
            pseudoPatientId?: number | null | undefined;
            pseudoExaminationId?: number | null | undefined;
            metadataImported?: boolean | undefined;
            fileSize?: number | undefined;
            rawFile?: string | undefined;
            uploadJob?: {
                id: string;
                status: 'pending' | 'processing' | 'anonymized' | 'error' | 'lost' | string;
                ingestMode?: string | undefined;
                sourceSystem?: string | undefined;
                sourceCenterKey?: string | null | undefined;
                originalFilename?: string | undefined;
                sourceFilePersisted?: boolean | undefined;
                cleanupStatus?: string | undefined;
                errorDetail?: string | undefined;
                createdAt?: string | null | undefined;
                updatedAt?: string | null | undefined;
            } | null | undefined;
            quarantined?: boolean | undefined;
            quarantineId?: string | undefined;
            quarantineDirectoryKey?: string | undefined;
            quarantineDirectoryLabel?: string | undefined;
            errorDetail?: string | undefined;
        }[];
        needsValidationIds: number[];
    } & import("pinia").PiniaCustomStateProperties<AnonymizationState>;
}, {
    /** Gets the next anonymization file + its metadata */
    fetchNext(lastId?: number): Promise<any>;
    patchPdf(payload: {
        id: number;
        [key: string]: any;
    }): Promise<any>;
    patchVideo(payload: {
        id: number;
        [key: string]: any;
    }): Promise<any>;
    fetchPendingAnonymizations(): [boolean];
    /**
     * Fetch overview of all uploaded files with their statuses
     */
    fetchOverview(): Promise<FileItem[]>;
    /**
     * Start anonymization for a specific file
     */
    startAnonymization(id: number): Promise<boolean>;
    /**
     * Start polling status for a specific file
     */
    startPolling(id: number): void;
    /**
     * Stop polling for a specific file
     */
    stopPolling(id: number): void;
    /**
     * Stop all polling
     */
    stopAllPolling(): void;
    /**
     * Set current item for validation (called when clicking "Validate")
     */
    setCurrentForValidation(id: number, mediaType: string): Promise<SensitiveMeta | null | undefined>;
    /**
     * Refresh overview data
     */
    refreshOverview(): Promise<void>;
    /**
     * Re-import a video file to regenerate metadata
     */
    reimportVideo(fileId: number): Promise<boolean>;
    /**
     * Re-import a PDF file to regenerate metadata
     * Follows the same pattern as reimportVideo for consistency
     */
    reimportPdf(fileId: number): Promise<boolean>;
}>;
