export interface Patient {
    id: number;
    first_name: string;
    name: string;
    dob: string;
    email?: string;
    phone?: string;
    is_real_person: boolean;
    gender_id?: number;
    center_id?: number;
    patient_hash?: string;
    examination_hash?: string;
    patient_gender?: string;
    center?: string;
    examiners?: string[];
    endoscope_type?: string;
    endoscope_sn?: string;
    created_at?: string;
    updated_at?: string;
}
export interface PatientVideo {
    id: number;
    original_file_name: string;
    file_path?: string;
    video_url?: string;
    duration?: number;
    status?: 'pending' | 'annotated' | 'validated';
    sensitive_meta_id?: number;
    created_at?: string;
    updated_at?: string;
}
export interface PatientReport {
    id: number;
    file_name: string;
    file_path?: string;
    file_url?: string;
    file_type: 'pdf' | 'doc' | 'docx';
    status?: 'pending' | 'processed' | 'validated';
    anonymized_text?: string;
    sensitive_meta_id?: number;
    created_at?: string;
    updated_at?: string;
}
export interface PatientExamination {
    id: number;
    date_start: string;
    date_stop?: string;
    examination_id: number;
    examination_name?: string;
    patient_id: number;
    report_file_id?: number;
    video_file_id?: number;
    status?: 'in_progress' | 'completed' | 'cancelled';
    findings?: PatientFinding[];
}
export interface PatientFinding {
    id: number;
    examination_id: number;
    patient_id: number;
    finding_type: string;
    location?: string;
    morphology?: string;
    intervention?: string;
    notes?: string;
    confidence_score?: number;
    validated?: boolean;
    created_at?: string;
}
export interface SensitiveMetaData {
    id: number;
    patient_first_name: string;
    patient_last_name: string;
    patient_dob: string;
    examination_date: string;
    patient_gender?: string;
    center?: string;
    examiners?: string[];
    endoscope_type?: string;
    endoscope_sn?: string;
    patient_hash?: string;
    examination_hash?: string;
}
export interface PatientWithMedia {
    patient: Patient;
    videos: PatientVideo[];
    reports: PatientReport[];
    examinations: PatientExamination[];
    sensitive_meta?: SensitiveMetaData;
    last_updated?: string;
}
export interface PatientSearchFilters {
    name?: string;
    dob?: string;
    center?: string;
    status?: 'pending' | 'annotated' | 'validated' | 'all';
    has_videos?: boolean;
    has_reports?: boolean;
    date_range?: {
        start: string;
        end: string;
    };
}
export interface PatientUpdatePayload {
    id: number;
    first_name?: string;
    name?: string;
    dob?: string;
    examination_date?: string;
    patient_gender?: string;
    center?: string;
}
export declare const usePatientStore: import("pinia").StoreDefinition<"patient", import("pinia")._UnwrapAll<Pick<{
    patients: import("vue").Ref<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[], Patient[] | {
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    currentPatient: import("vue").Ref<{
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    } | null, PatientWithMedia | {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    } | null>;
    patientCache: import("vue").Ref<Map<number, {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    }> & Omit<Map<number, PatientWithMedia>, keyof Map<any, any>>, Map<number, PatientWithMedia> | (Map<number, {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    }> & Omit<Map<number, PatientWithMedia>, keyof Map<any, any>>)>;
    searchFilters: import("vue").Ref<{
        name?: string | undefined;
        dob?: string | undefined;
        center?: string | undefined;
        status?: "pending" | "annotated" | "validated" | "all" | undefined;
        has_videos?: boolean | undefined;
        has_reports?: boolean | undefined;
        date_range?: {
            start: string;
            end: string;
        } | undefined;
    }, PatientSearchFilters | {
        name?: string | undefined;
        dob?: string | undefined;
        center?: string | undefined;
        status?: "pending" | "annotated" | "validated" | "all" | undefined;
        has_videos?: boolean | undefined;
        has_reports?: boolean | undefined;
        date_range?: {
            start: string;
            end: string;
        } | undefined;
    }>;
    loading: import("vue").Ref<boolean, boolean>;
    saving: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    lastFetchedId: import("vue").Ref<number | null, number | null>;
    totalPatients: import("vue").Ref<number, number>;
    currentPage: import("vue").Ref<number, number>;
    pageSize: import("vue").Ref<number, number>;
    isCurrentPatientAnnotated: import("vue").ComputedRef<boolean>;
    filteredPatients: import("vue").ComputedRef<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    paginatedPatients: import("vue").ComputedRef<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    totalPages: import("vue").ComputedRef<number>;
    fetchPatients: (filters?: PatientSearchFilters) => Promise<void>;
    fetchPatientWithMedia: (patientId: number) => Promise<PatientWithMedia | null>;
    updatePatientSensitiveMeta: (patientId: number, updateData: Partial<SensitiveMetaData>, mediaType?: 'video' | 'pdf') => Promise<boolean>;
    fetchNextPatientForAnnotation: (mediaType?: 'video' | 'pdf') => Promise<PatientWithMedia | null>;
    addPatientVideo: (patientId: number, videoData: Partial<PatientVideo>) => Promise<boolean>;
    addPatientReport: (patientId: number, reportData: Partial<PatientReport>) => Promise<boolean>;
    searchPatients: (searchTerm: string) => Patient[];
    setSearchFilters: (filters: PatientSearchFilters) => void;
    clearSearch: () => void;
    setCurrentPage: (page: number) => void;
    clearCurrentPatient: () => void;
    clearCache: () => void;
    clearError: () => void;
    getPatientDisplayName: (patient: Patient) => string;
    isPatientDataComplete: (patient: PatientWithMedia) => boolean;
    getPatientProgress: (patient: PatientWithMedia) => {
        videosAnnotated: number;
        totalVideos: number;
        reportsProcessed: number;
        totalReports: number;
        overallProgress: number;
    };
}, "loading" | "error" | "saving" | "lastFetchedId" | "patients" | "currentPatient" | "patientCache" | "searchFilters" | "totalPatients" | "currentPage" | "pageSize">>, Pick<{
    patients: import("vue").Ref<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[], Patient[] | {
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    currentPatient: import("vue").Ref<{
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    } | null, PatientWithMedia | {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    } | null>;
    patientCache: import("vue").Ref<Map<number, {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    }> & Omit<Map<number, PatientWithMedia>, keyof Map<any, any>>, Map<number, PatientWithMedia> | (Map<number, {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    }> & Omit<Map<number, PatientWithMedia>, keyof Map<any, any>>)>;
    searchFilters: import("vue").Ref<{
        name?: string | undefined;
        dob?: string | undefined;
        center?: string | undefined;
        status?: "pending" | "annotated" | "validated" | "all" | undefined;
        has_videos?: boolean | undefined;
        has_reports?: boolean | undefined;
        date_range?: {
            start: string;
            end: string;
        } | undefined;
    }, PatientSearchFilters | {
        name?: string | undefined;
        dob?: string | undefined;
        center?: string | undefined;
        status?: "pending" | "annotated" | "validated" | "all" | undefined;
        has_videos?: boolean | undefined;
        has_reports?: boolean | undefined;
        date_range?: {
            start: string;
            end: string;
        } | undefined;
    }>;
    loading: import("vue").Ref<boolean, boolean>;
    saving: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    lastFetchedId: import("vue").Ref<number | null, number | null>;
    totalPatients: import("vue").Ref<number, number>;
    currentPage: import("vue").Ref<number, number>;
    pageSize: import("vue").Ref<number, number>;
    isCurrentPatientAnnotated: import("vue").ComputedRef<boolean>;
    filteredPatients: import("vue").ComputedRef<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    paginatedPatients: import("vue").ComputedRef<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    totalPages: import("vue").ComputedRef<number>;
    fetchPatients: (filters?: PatientSearchFilters) => Promise<void>;
    fetchPatientWithMedia: (patientId: number) => Promise<PatientWithMedia | null>;
    updatePatientSensitiveMeta: (patientId: number, updateData: Partial<SensitiveMetaData>, mediaType?: 'video' | 'pdf') => Promise<boolean>;
    fetchNextPatientForAnnotation: (mediaType?: 'video' | 'pdf') => Promise<PatientWithMedia | null>;
    addPatientVideo: (patientId: number, videoData: Partial<PatientVideo>) => Promise<boolean>;
    addPatientReport: (patientId: number, reportData: Partial<PatientReport>) => Promise<boolean>;
    searchPatients: (searchTerm: string) => Patient[];
    setSearchFilters: (filters: PatientSearchFilters) => void;
    clearSearch: () => void;
    setCurrentPage: (page: number) => void;
    clearCurrentPatient: () => void;
    clearCache: () => void;
    clearError: () => void;
    getPatientDisplayName: (patient: Patient) => string;
    isPatientDataComplete: (patient: PatientWithMedia) => boolean;
    getPatientProgress: (patient: PatientWithMedia) => {
        videosAnnotated: number;
        totalVideos: number;
        reportsProcessed: number;
        totalReports: number;
        overallProgress: number;
    };
}, "isCurrentPatientAnnotated" | "filteredPatients" | "paginatedPatients" | "totalPages">, Pick<{
    patients: import("vue").Ref<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[], Patient[] | {
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    currentPatient: import("vue").Ref<{
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    } | null, PatientWithMedia | {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    } | null>;
    patientCache: import("vue").Ref<Map<number, {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    }> & Omit<Map<number, PatientWithMedia>, keyof Map<any, any>>, Map<number, PatientWithMedia> | (Map<number, {
        patient: {
            id: number;
            first_name: string;
            name: string;
            dob: string;
            email?: string | undefined;
            phone?: string | undefined;
            is_real_person: boolean;
            gender_id?: number | undefined;
            center_id?: number | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        };
        videos: {
            id: number;
            original_file_name: string;
            file_path?: string | undefined;
            video_url?: string | undefined;
            duration?: number | undefined;
            status?: "pending" | "annotated" | "validated" | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        reports: {
            id: number;
            file_name: string;
            file_path?: string | undefined;
            file_url?: string | undefined;
            file_type: 'pdf' | 'doc' | 'docx';
            status?: "pending" | "processed" | "validated" | undefined;
            anonymized_text?: string | undefined;
            sensitive_meta_id?: number | undefined;
            created_at?: string | undefined;
            updated_at?: string | undefined;
        }[];
        examinations: {
            id: number;
            date_start: string;
            date_stop?: string | undefined;
            examination_id: number;
            examination_name?: string | undefined;
            patient_id: number;
            report_file_id?: number | undefined;
            video_file_id?: number | undefined;
            status?: "in_progress" | "completed" | "cancelled" | undefined;
            findings?: {
                id: number;
                examination_id: number;
                patient_id: number;
                finding_type: string;
                location?: string | undefined;
                morphology?: string | undefined;
                intervention?: string | undefined;
                notes?: string | undefined;
                confidence_score?: number | undefined;
                validated?: boolean | undefined;
                created_at?: string | undefined;
            }[] | undefined;
        }[];
        sensitive_meta?: {
            id: number;
            patient_first_name: string;
            patient_last_name: string;
            patient_dob: string;
            examination_date: string;
            patient_gender?: string | undefined;
            center?: string | undefined;
            examiners?: string[] | undefined;
            endoscope_type?: string | undefined;
            endoscope_sn?: string | undefined;
            patient_hash?: string | undefined;
            examination_hash?: string | undefined;
        } | undefined;
        last_updated?: string | undefined;
    }> & Omit<Map<number, PatientWithMedia>, keyof Map<any, any>>)>;
    searchFilters: import("vue").Ref<{
        name?: string | undefined;
        dob?: string | undefined;
        center?: string | undefined;
        status?: "pending" | "annotated" | "validated" | "all" | undefined;
        has_videos?: boolean | undefined;
        has_reports?: boolean | undefined;
        date_range?: {
            start: string;
            end: string;
        } | undefined;
    }, PatientSearchFilters | {
        name?: string | undefined;
        dob?: string | undefined;
        center?: string | undefined;
        status?: "pending" | "annotated" | "validated" | "all" | undefined;
        has_videos?: boolean | undefined;
        has_reports?: boolean | undefined;
        date_range?: {
            start: string;
            end: string;
        } | undefined;
    }>;
    loading: import("vue").Ref<boolean, boolean>;
    saving: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    lastFetchedId: import("vue").Ref<number | null, number | null>;
    totalPatients: import("vue").Ref<number, number>;
    currentPage: import("vue").Ref<number, number>;
    pageSize: import("vue").Ref<number, number>;
    isCurrentPatientAnnotated: import("vue").ComputedRef<boolean>;
    filteredPatients: import("vue").ComputedRef<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    paginatedPatients: import("vue").ComputedRef<{
        id: number;
        first_name: string;
        name: string;
        dob: string;
        email?: string | undefined;
        phone?: string | undefined;
        is_real_person: boolean;
        gender_id?: number | undefined;
        center_id?: number | undefined;
        patient_hash?: string | undefined;
        examination_hash?: string | undefined;
        patient_gender?: string | undefined;
        center?: string | undefined;
        examiners?: string[] | undefined;
        endoscope_type?: string | undefined;
        endoscope_sn?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    }[]>;
    totalPages: import("vue").ComputedRef<number>;
    fetchPatients: (filters?: PatientSearchFilters) => Promise<void>;
    fetchPatientWithMedia: (patientId: number) => Promise<PatientWithMedia | null>;
    updatePatientSensitiveMeta: (patientId: number, updateData: Partial<SensitiveMetaData>, mediaType?: 'video' | 'pdf') => Promise<boolean>;
    fetchNextPatientForAnnotation: (mediaType?: 'video' | 'pdf') => Promise<PatientWithMedia | null>;
    addPatientVideo: (patientId: number, videoData: Partial<PatientVideo>) => Promise<boolean>;
    addPatientReport: (patientId: number, reportData: Partial<PatientReport>) => Promise<boolean>;
    searchPatients: (searchTerm: string) => Patient[];
    setSearchFilters: (filters: PatientSearchFilters) => void;
    clearSearch: () => void;
    setCurrentPage: (page: number) => void;
    clearCurrentPatient: () => void;
    clearCache: () => void;
    clearError: () => void;
    getPatientDisplayName: (patient: Patient) => string;
    isPatientDataComplete: (patient: PatientWithMedia) => boolean;
    getPatientProgress: (patient: PatientWithMedia) => {
        videosAnnotated: number;
        totalVideos: number;
        reportsProcessed: number;
        totalReports: number;
        overallProgress: number;
    };
}, "clearCache" | "clearError" | "fetchPatients" | "fetchPatientWithMedia" | "updatePatientSensitiveMeta" | "fetchNextPatientForAnnotation" | "addPatientVideo" | "addPatientReport" | "searchPatients" | "setSearchFilters" | "clearSearch" | "setCurrentPage" | "clearCurrentPatient" | "getPatientDisplayName" | "isPatientDataComplete" | "getPatientProgress">>;
