apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lx-annotate-data
  namespace: lx-annotate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
