# Generated by Django 6.0.3 on 2026-09-14 15:08
from __future__ import annotations

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endoreg_db", "0078_video_joined_dataset"),
        ("lx_annotate", "0008_aidatasetsplitplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoTranscodeJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.UUIDField(unique=True)),
                (
                    "option",
                    models.CharField(
                        choices=[
                            ("replace_processed", "Replace processed derivative"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("lost", "Lost"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("stage", models.CharField(default="queued", max_length=32)),
                ("source_name", models.CharField(max_length=500)),
                ("source_sha256", models.CharField(max_length=64)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("before_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("after_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("saved_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transcode_jobs",
                        to="endoreg_db.videofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "running"])),
                        fields=("video",),
                        name="lx_one_active_video_transcode",
                    )
                ],
            },
        ),
    ]
